name: personalcard
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
  - family: Pacifico
    fonts:
    - asset: assets/fonts/Pacifico-Regular.ttf

  - family: SourceSansPro
    fonts:
    - asset: assets/fonts/SourceSansPro-Regular.ttf  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
